### ISSUE TITLE
Time Zone Info in Client Hint?

### ISSUE THREAD

**Issue by karlhorky** [ben-allen/locale-extensions#11]
Hi, first of all, thanks for this proposal, looks useful 👍 

Just coming from [this discussion on Twitter/X](https://twitter.com/romulocintra/status/1727704010994384943) with @romulocintra and this proposal was mentioned there in a discussion about sending time zone information as a client hint for [server-side rendering Dates in a user's time zone](https://www.jacobparis.com/content/remix-ssr-dates).

Does this also offer the possibility of sending the user's time zone info in a client hint as well? (or maybe it is out of scope for this proposal?)

Screenshot of the discussion for those not on Twitter/X:

![Screenshot 2024-01-18 at 18 48 02](https://github.com/ben-allen/locale-extensions/assets/1935696/fae13e89-2e42-4ef0-acc4-d652d75a4af4)

**Comment by ben-allen** [comment]
Time zone is currently out of scope for this proposal -- we're looking at a limited range of user preferences that aren't exposed elsewhere.

**Comment by karlhorky** [comment]
Ok thanks for the info, closing.
